#
# Make sure temp directories used by install is always available
#

- name: create install dir
  file: path="{{ install_dir }}" state=directory

- name: create temporary install dir
  file: path="{{ install_temp_dir }}" state=directory

- name: get PATH
  shell: echo $PATH
  register: path

- name: download kubectl
  include: kubectl.yml

- name: download helm
  include: helm.yml

- name: init helm
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    helm init --client-only

#
# Based on documentation from https://zero-to-jupyterhub.readthedocs.io/en/latest/
#
- name: Add JupyterHub Helm chart repository
  ignore_errors: yes
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
    helm repo update > /dev/null

- name: Create JupyterHub helm chart configuration
  template:
    src: jupyterhub-config.yaml.j2
    dest: "{{ install_temp_dir }}/jupyterhub-config.yaml"
    mode: 0644

- name: Install JupyterHub
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    helm upgrade --install --force hub jupyterhub/jupyterhub --namespace {{ jupyterhub.namespace }} --version {{ jupyterhub.helm_version }} --values {{ install_temp_dir }}/jupyterhub-config.yaml

- name: Create JupyterHub NFS service descriptor
  template:
    src: nfs-deployment-icp.yaml.j2
    dest: "{{ install_temp_dir }}/nfs-deployment-icp.yaml"
    mode: 0644

- name: Create NFS provisioner
  environment:
    PATH: "{{ path.stdout }}:/opt/ansible"
  shell: |
    kubectl apply -f {{ install_temp_dir }}/nfs-deployment-icp.yaml
