apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jupyterlabs.jupterlab.ibm.com
spec:
  group: jupterlab.ibm.com
  names:
    kind: Jupyterlab
    listKind: JupyterlabList
    plural: jupyterlabs
    singular: jupyterlab
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
